import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import qmc

def qmc_sampling(parameters, n_points, force_edges=True):
    """
    Generate a Quasi-Monte Carlo (QMC) sample using the Halton sequence.

    This function creates a multidimensional sample based on the provided parameter
    definitions, scaling each dimension to its specified bounds and types.

    Parameters
    ----------
    parameters : dict
        A dictionary defining the search space. Each key is a parameter name, 
        and the value is another dict containing:
        - 'type': str ('float', 'int', or 'categoric')
        - 'l_bound': float/int (required for numeric types)
        - 'u_bound': float/int (required for numeric types)
        - 'categories': list (required for 'categoric' type)
    n_points : int
        The number of samples to generate.
    force_edges : bool, default=True
        If True, the samples are rescaled so that the minimum and maximum 
        generated values exactly match the specified bounds. 
        If False, values are kept in the [0, 1] probability space before scaling.

    Returns
    -------
    pd.DataFrame
        A DataFrame where each column corresponds to a parameter and each 
        row is a generated sample point.
    """
    sampler = qmc.Halton(d=len(parameters), seed=42)
    sample = sampler.random(n=n_points)

    sample_dict = {}
    for index, p in enumerate(parameters.keys()):

        values = sample[:, index]

        if force_edges:
            v_min, v_max = values.min(), values.max()
        elif force_edges==False:
            v_min, v_max = 0.0, 1.0
        else:
            return print('forced_edges must be True or False')

        p_type = parameters[p]['type']

        if p_type == 'float':
            l_bound = parameters[p]['l_bound']
            u_bound = parameters[p]['u_bound']
            scaled = l_bound + (values - v_min) * (u_bound - l_bound) / (v_max - v_min)
            sample_dict[p] = scaled

        elif p_type == 'int':
            l_bound = parameters[p]['l_bound']
            u_bound = parameters[p]['u_bound']
            scaled = l_bound + (values - v_min) * (u_bound - l_bound) / (v_max - v_min)
            scaled = np.round(scaled).astype(int)
            sample_dict[p] = scaled

        elif p_type == 'categoric':
            v_min, v_max = values.min(), values.max()
            categories = parameters[p]['categories']
            l_bound = 0
            u_bound = len(categories)-1
            scaled = l_bound + (values - v_min) * (u_bound - l_bound) / (v_max - v_min)
            scaled = np.round(scaled).astype(int).tolist()
            scaled = [categories[v] for v in scaled]
            sample_dict[p] = scaled
        else:
            return print(f'{p}: type must be float, int or categoric')
    df = pd.DataFrame(sample_dict)
    return df

def plot_qmc_sampling(df):
    """
    Create a scatter plot matrix of the numerical variables in the sample.

    This visualizes the space-filling properties of the QMC sampling by 
    plotting each numeric parameter against every other numeric parameter 
    in a grid of subplots.

    Parameters
    ----------
    df : pd.DataFrame
        The DataFrame generated by `qmc_sampling`.
    """
    num_df = df.select_dtypes(include='number')
    n_vars = len(num_df.columns)

    plt.figure(figsize=(3*n_vars, 3*n_vars))
    plot = 1
    for i, var_1 in enumerate(num_df.columns):
        for j, var_2 in enumerate(num_df.columns):
            if i >= j:
                plt.subplot(n_vars, n_vars, plot)
                plt.scatter(num_df[var_1], num_df[var_2])
                plt.xlabel(var_1)
                plt.ylabel(var_2)
            plot +=1
    plt.tight_layout()
    plt.show()